### ISSUE TITLE
Monster Blind 0 consumables

### ISSUE THREAD

**Issue by eslavidaloca** [Mysthaps/BalatroMods#2]
Hi, after defeating The Monster Blind doesn't return consumable slots. 

I don't know if it's designed to be like this. If so you can close my issue hahaha

![image](https://github.com/Mysthaps/BalatroMods/assets/56058934/748ec3fa-30df-4c14-934e-3071542e444b)

**Comment by Mysthaps** [comment]
Hey! 
Sorry for the late response, but this issue has been fixed on the dev branch of Steamodded.
https://github.com/Steamopollys/Steamodded/tree/dev

You can either use this version with Lovely, or wait for the official release of Steamodded 0.9.9.

**Comment by eslavidaloca** [comment]
Thank you for your response, I'll try that :D

**Comment by Mysthaps** [comment]
forgot to say, but this has been fixed without needing to update Steamodded!
https://github.com/Mysthaps/BalatroMods/blob/main/Changelog.md#april-28th-2024
